### ISSUE TITLE
Issues with installing klov and mongoDB

### ISSUE THREAD

**Issue by jayasriram** [extent-framework/klov#10]
I have 2 issues.
1.)I am using klov 0.1.1 and extent report 3.1.2 but I am getting error **(bind() failed errno:10048)** while starting the mongoDB and MongoSocketOpenException while running the executing the klov jar
2.) The link for the demo throws up an internal server error and there is not much information available elsewhere as well.
![klov_error](https://user-images.githubusercontent.com/46928916/51541652-462c3f80-1e51-11e9-8d8c-50103c405e87.JPG)
![mongodberror](https://user-images.githubusercontent.com/46928916/51541657-475d6c80-1e51-11e9-9fd3-887f435b7178.JPG)

**Comment by anshooarora** [comment]
It looks to me that something is not right in your initialization.  Please share your code.

Issue 1 - is because the connection to mongodb failed, reason: connection timeout
Issue 2 - something else is running on this port already

Also, since I am unable to support version 3 API and Klov, I would recommend upgrading to version extentreports:4.0 and klov:0.2.

**Comment by jayasriram** [comment]
Does version 4.0 support parallel execution and that was the reason i am using version 3?
And i saw that one of your team members have mentioned that this version is not available for .NET (mentioned here : https://github.com/extent-framework/klov-server/issues/2)

**Comment by anshooarora** [comment]
Hmm, are you using Java or .NET?  .Net 4 supports parallel execution.

**Comment by jayasriram** [comment]
I am using .NET version 4 but I was talking about extent reports version 4.
Does extent report version 4 support parallel execution along with klov?

**Comment by jayasriram** [comment]
Do u have any parallel test examples using extent reports implementing BDD?

**Comment by anshooarora** [comment]
> Does extent report version 4 support parallel execution along with klov?

Parallel, yes. Klov integration is yet to be implemented. 

> Do u have any parallel test examples using extent reports implementing BDD?

Do you use Specflow?

Please create new ticket for your question and this conversation is now unrelated to the original question.

**Comment by jayasriram** [comment]
Sure, I have raised a new ticket and thanks for the information.
