### ISSUE TITLE
Need to edit the Dashboard for the Klov server 0.2.2 - 0.2.3

### ISSUE THREAD

**Issue by nikhilGupta24** [extent-framework/klov#11]
Hi Team 

we have developed a keyword driven framework and are using the Extent Report stack for reporting (including the Klov server) 

Can you guide us on,  

1. How to edit/customise the Dashboard that we have for Klov. The number which come up and the graphs. -- Like we want to be selective on the logic on which these values are populated.... 

2. What is the build performance graph that comes up on the Klov server dashboard ? We would like to have some information in regards to that as well, like what exactly it populates and plots on the dashboard.

3. the could schemes - if possible - how to edit them, as the failure count on the Failure trend chart on the Klov server is BLUE -- Should be RED in accordance to the color scheme of the Ring graph representing the last build.

![klov](https://user-images.githubusercontent.com/43847425/51544231-75f53a80-1e85-11e9-9bac-6fbbeaccbfb6.PNG)

Thanking you

Regards
Nikhil

**Comment by anshooarora** [comment]
> How to edit/customise the Dashboard that we have for Klov. The number which come up and the graphs. -- Like we want to be selective on the logic on which these values are populated.

this functionality will be available from the project administration, you will be able to select which data-point level to configure your statistics upon. 

> What is the build performance graph that comes up on the Klov server dashboard ? We would like to have some information in regards to that as well, like what exactly it populates and plots on the dashboard.

time taken to execute the build.

> the could schemes - if possible - how to edit them, as the failure count on the Failure trend chart on the Klov server is BLUE -- Should be RED in accordance to the color scheme of the Ring graph representing the last build.

Will fix..

For future reference, please create only 1 ticket per issue.

**Comment by nikhilGupta24** [comment]
Hi

Thanks for the prompt reply ! 👍 

> **Project Administration** 
>Where to configure this ? 
>From the code base -- Extent Library
>OR 
>Configuring something in the Klov JAR setup (property files -- application.properties)  ??

A bit more insight would be highly appreciated. 

Thanking you

Regards
Nikhil

**Comment by anshooarora** [comment]
Project administration will be available from the Klov side.

**Comment by anshooarora** [comment]
>How to edit/customise the Dashboard that we have for Klov. The number which come up and the graphs. -- Like we want to be selective on the logic on which these values are populated....

will be available start `0.2.4` via "User -> Project Settings"

> the could schemes - if possible - how to edit them, as the failure count on the Failure trend chart on the Klov server is BLUE -- Should be RED in accordance to the color scheme of the Ring graph representing the last build.

fixed
