### ISSUE TITLE
Tests in state "error" don't have a background

### ISSUE THREAD

**Issue by letmejustfixthat** [extent-framework/klov#12]
A test being in error (not fail) state doesn't have a bubble/background in the test list
 (Builds -> Select a Build -> Left column/List of tests)
![screenhunter_179 jan 24 07 31](https://user-images.githubusercontent.com/12950399/51659197-23fa0500-1faa-11e9-9e77-b97a1bdfccfe.jpg)

**Comment by anshooarora** [comment]
This has been fixed.  Will release `0.2.4` today.
