### ISSUE TITLE
Can you provide examples for parallel execution using Specflow?

### ISSUE THREAD

**Issue by jayasriram** [extent-framework/klov#13]
Hi, I was wondering if you could provide me some examples to implement BDD and use Extent Reports along with parallel execution of these tests.
I am currently using Specflow and I have integrated Extent Reports which run sequentially but I am trying to make it run in parallel and I do not see any examples elsewhere. 
Your help would be much appreciated.

**Comment by anshooarora** [comment]
Similar to: 
https://github.com/extent-framework/extentreports-csharp/issues/30

I will try to release the adapter by next week, would appreciate if you could collaborate in the effort. Cheers.
