### ISSUE TITLE
Content automatically adapts to screen size

### ISSUE THREAD

**Issue by 317174106** [extent-framework/klov#14]
I am using 0.2.4.

My log content is very large and long, so......it seems that this display like below is not very friendly. 

I need to swipe right to show all content.

Can the log content adapt to screen size automatically ?

![large](https://user-images.githubusercontent.com/25921468/51907816-f32f2b00-2402-11e9-9273-c20b19813e55.png)

**Comment by anshooarora** [comment]
Fixed, will be available in the next version.  Also, I would recommend using the below as the code will be prettified and formatted without any additional css:

```
test.pass(MarkupHelper.createCodeBlock(json, CodeLanguage.JSON));
```

[See here](http://extentreports.com/docs/versions/4/java/#markup-helpers-codeblock)
