### ISSUE TITLE
Need to tag the "Error States" at the Child Test level. 

### ISSUE THREAD

**Issue by nikhilGupta24** [extent-framework/klov#15]
Can we have a tagging for the "Error Analysis" at the Child Test level. ??
Right now, it happens at the Parent Test Level (as shown in the image)

![klov_errorstates](https://user-images.githubusercontent.com/43847425/51986246-d3147000-24c5-11e9-98bd-11119968a48f.PNG)

We have associated a lot of tests (Child Tests) to a single parent test (We have multiple parent tests executing) -- which, as of now we, can not specifically mark a error state against.  It is marked for the whole parent test.

This would greatly help us to analyse only the concerned Child Tests.

Thanking you

Regards
Nikhil

**Comment by anshooarora** [comment]
Now included, will be part of the next release
