### ISSUE TITLE
The "Analysis Strategy" is not patching onto the builds information screen

### ISSUE THREAD

**Issue by nikhilGupta24** [extent-framework/klov#16]
Hi
Klov - 0.2.4 | MongoDB - 4.0.5 | ExtentReports : 4.0.5

I have chosen the error analysis at level "1" which is the child test level.
The Dashboard updates perfectly with the graph at the child test level as shown in the image below : 

![klov_analysisstrategy_1](https://user-images.githubusercontent.com/43847425/51986964-639f8000-24c7-11e9-811c-18034eeb2fe4.PNG)
 
But in the "builds" screen, the statistics are at the Parent Level only. 

There are 152 test (Child) attached to 43 Parent Tests. Refer the image below : 

![klov_analysisstrategy](https://user-images.githubusercontent.com/43847425/51987036-947fb500-24c7-11e9-8267-440a4466264a.PNG)
 
Can we consistency once we chose the type of analysis strategy we want ?

Or is there something we are missing out on from the ExtentReports | Klov  Library ?

Please verify the same

Thanking you

Regards
Nikhil

**Comment by nikhilGupta24** [comment]
Hi Team !

Greetings. :)

Just wanted to check on the **Timelines for the next community release** for Klov server. 

Thanking you and regards
Nikhil

**Comment by anshooarora** [comment]
Hi - this was fixed in version 0.2.6.
