### ISSUE TITLE
Un-tagging the "Error States"

### ISSUE THREAD

**Issue by nikhilGupta24** [extent-framework/klov#17]
Hi

We are doing the analysis of the failed test cases from Klov server, thus we use Error states for tagging the issues.

But apparently we are not able to un-tag the error states from the tagged test.

Is there a way in Klov we can do that ??

How is the lifecycle is managed for a failing test case which is being tagged with an error state. Will it automatically be removed once it passes in the next build OR do we manually analyse and remove the tag (if possible) ?

Thanking you

Regards
Nikhil

**Comment by anshooarora** [comment]
Now included, will be part of the next release.

To unselect, simply select the same error-state for the test.
