### ISSUE TITLE
How to login to klov server? server.admin.name in property file didnt work

### ISSUE THREAD

**Issue by girinath** [extent-framework/klov#18]
I have set up the Klov server(0.2.4) with mongoDB (4.0.5), I am able to launch the Klov server page (localhost:80), but not sure how to login as i don't have any username or password. server.admin.name set in property file didn't work.

I have used 0.1.1 without login. Is it possible to disable login page ? if not how can i create users to login? 

Note : I don't have email server setup.

**Comment by foursyth** [comment]
Please refer [docs](http://extentreports.com/docs/versions/4/klov/).

**Comment by girinath** [comment]
Using klovadmin/password didnt work as mentioned in docs. getting invalid password error.
