### ISSUE TITLE
Klov-2.0 with .net 3.1 compatibility

### ISSUE THREAD

**Issue by ashwin-ak** [extent-framework/klov#2]
Hi,

Is klov-2.0 compatible with .net 3.1. I am unable to see any server builds.

Thanks,
Ashwin

**Comment by foursyth** [comment]
Hello @ashwin-ak 

Klov 0.2.0 is compatible with version 4 only.  This version is currently not available for .NET but development is expected to start in January 2019.

**Comment by foursyth** [comment]
@anshooarora Please close this
