### ISSUE TITLE
Klov server setup

### ISSUE THREAD

**Issue by sebinjqburst** [extent-framework/klov#20]
I am new to Klov and I tried to set up the server by setting up MongoDB. I am able to view and login to klov with the URL _http://localhost:82_ (I am using port 82 as 80 was shown as already in use). But when I run the test, the projects are not created.

Please find the klov related code I am using:
ExtentKlovReporter klov = new ExtentKlovReporter("Test Automation","Test");
klov.initMongoDbConnection("localhost", 27017);
klov.initKlovServerConnection("http://localhost/82");(I tried both _http://localhost_ and _http://localhost/82_, but none works)

Am I missing something?

**Comment by anshooarora** [comment]
Have you attached klov like so:

```
extent.attachReporter(klov)
```

**Comment by sebinjqburst** [comment]
Oops. That was the issue!! :-) Thanks a lot for the immediate response.
