### ISSUE TITLE
I'm getting a 500 internal error when I tried to navigate to dashboard.

### ISSUE THREAD

**Issue by tjj006** [extent-framework/klov#25]
Sorry! the page you are looking for doesn't exist.
Go back to home or contact us about a problem.

-- 500 Internal Server Error --

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.util.NoSuchElementException: No value present

> I can login, but no project could be selected. Everything is blank.
When I tried to open the dashboard, it displayed the 500-internal error.
Any idea?

![image](https://user-images.githubusercontent.com/1046621/55683942-2d272b00-5978-11e9-9bbd-e2f62d5ad6ff.png)

**Comment by foursyth** [comment]
@tjj006 

what is the ExtentReports version?  Klov version?

**Comment by ThinkPowerful** [comment]
I am facing the same issue as above. Is there and update on this? Below is the dependency which I am using.

<dependency>
			<groupId>com.aventstack</groupId>
			<artifactId>extentreports</artifactId>
			<version>4.0.9</version>
			<scope>provided</scope>
		</dependency>

**Comment by ThinkPowerful** [comment]
> Sorry! the page you are looking for doesn't exist.
> Go back to home or contact us about a problem.
> 
> -- 500 Internal Server Error --
> 
> org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.util.NoSuchElementException: No value present
> 
> > I can login, but no project could be selected. Everything is blank.
> > When I tried to open the dashboard, it displayed the 500-internal error.
> > Any idea?
> 
> ![image](https://user-images.githubusercontent.com/1046621/55683942-2d272b00-5978-11e9-9bbd-e2f62d5ad6ff.png)

Hi, Did you manage to resolve this? Kindly assist:)

**Comment by anshooarora** [comment]
All - are you still seeing this issue?

**Comment by jn1888** [comment]
Hey @anshooarora I am seeing this error when I try to click on any link to get into the specific tests. I have the following dependencies in my project:

extentreports - 4.1.6
extentreports-testng-adapter - 1.0.6
extentreports-cucumber4-adapter - 1.0.12

On the Dashboard, when I click on anything under Test Activity, I get this 500 error.

**Comment by jn1888** [comment]
@anshooarora Another issue I am seeing is that even when a test fails, it is tagged as Passed:
![image](https://user-images.githubusercontent.com/55323723/87863292-993c6100-c927-11ea-8a56-6ffe89a45327.png)

**Comment by anshooarora** [comment]
@jn1888 This version of Klov has been archived/removed and no longer supported.  The new version of Klov will be available in the next few days (supported by ExtentReports v5) and I would recommend you to upgrade.  All the issues in 0.2.x series have been resolved :)

**Comment by jn1888** [comment]
@anshooarora Thnx. Will keep an eye out.
