### ISSUE TITLE
Taking 3 to 5 minutes to load the klov report initial page and Launching the Klov report without Login (singon)

### ISSUE THREAD

**Issue by govindd18** [extent-framework/klov#28]
I need help here,

I am using Klov server 0.2.5.jar file and Mongodb 4.0, I'm facing the following issues.

1. While loading the klov report with all the projects after login, it is taking 3 to 5 minutes. Is there any way to improve the performance of the klov report to load the initial page.

2. Is there an option to launch the klov report without login (signon)

 Thanks in advance,
Govind.

**Comment by NallaSandeep** [comment]
@anshooarora Day by day, the MongoDB size is getting increased with the results, so it's taking more time to fetch the results. Can you please suggest us how the performance of the klov report can be improved? (By adding indexing at MongoDB? If so, on what fields?)

**Comment by juancarames** [comment]
i revive this topic. 
also i commented over the issue #55 because are related
@anshooarora 
tnx.

**Comment by anshooarora** [comment]
Please use version `0.2.9`.

**Comment by foursyth** [comment]
Also - please consider upgrading to Klov Professional and help the project stay alive. :)

@anshooarora
