### ISSUE TITLE
klov 0.2.1 - Dashboard not usaable during running tests

### ISSUE THREAD

**Issue by gedogarne** [extent-framework/klov#3]
Hi, we actually upgraded to extentReports 4.x, klov 0.2.1 and fresh mongoDB 4.x install.
extentReports are generated fine.
.klov reports are generated fine.

Only thing: Dashboard is not usable/reachable during testexecution.
After testexecution has finished everything works as expected incl. dashboard.

-> Error Msg.
2018-12-04 16:03:06.948 ERROR 10216 --- [tp1632413663-34] freemarker.runtime                       : Error executing FreeMarker template

freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> project.lastReport.status  [in template "project.select.ftl" at line 46, column 165]

----
Tip: It's the step after the last dot that caused this error, not those before it.
----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
        - Failed at: ${project.lastReport.status?string}  [in template "project.select.ftl" at line 46, column 163]

**Comment by foursyth** [comment]
@gedogarne we are aware of this, and was earlier raised by our customer.  Fix has already been released and we will add it to Git today.

**Comment by anshooarora** [comment]
Please use the latest, 0.2.2.  Thank you.
