### ISSUE TITLE
How to add the authentication in Klov to log into mongo DB.

### ISSUE THREAD

**Issue by prabha077** [extent-framework/klov#31]
My mongod is running in authentication mode. So, It needs a user name and password to log in.

When I download and run the klov jar. It is failing to start with the error saying unable to execute the query in mongo DB due to this authentication issue. So, How do I add authentication to the klov and build a new jar? Do we have any base project open for community that I can clone and edit for my purpose?

**Comment by anshooarora** [comment]
This can be done from application.properties like so:

```
spring.data.mongodb.uri = mongodb://content_rw:<secret password>@a.mongo.db:27017,b.mongo.db:27017,c.mongo.db:27017/contenttest?wtimeoutMS=300&connectTimeoutMS=500&socketTimeoutMS=200
```
