### ISSUE TITLE
Facing issue with Klov Server setup

### ISSUE THREAD

**Issue by kkashyap1707** [extent-framework/klov#33]
Hi anshu

I am facing the issue while setting up Klov Server.

Install mongodb
Downloaded Klov Server version 0.2.3
Updated the port number to 82 in properties file.

After running "java -jar klov-0.2.3.jar" command from terminal, error occurs.

Please help.

Error Screenshot:

![Screenshot from 2019-05-19 15-34-03](https://user-images.githubusercontent.com/4715140/57980669-eb47d500-7a4b-11e9-8b75-255ac6eb9325.png)

Mongo DB status:

![Screenshot from 2019-05-19 15-37-14](https://user-images.githubusercontent.com/4715140/57980680-fef33b80-7a4b-11e9-8c76-d514b2b09f3a.png)

**Comment by anshooarora** [comment]
This is due to MongoDB not gaining access to the document directory.  Please create the directory: "/data/db" or "C:\data\db".
