### ISSUE TITLE
Author/ Category & Device not present in Klov

### ISSUE THREAD

**Issue by vali92** [extent-framework/klov#34]
Hi,

I'm adding author,category & device on testcases using annotations, the same methods work on 
ExtentSparkReporter but when using ExtentKlovReporter are not displayed.

Klov version: 0.2.5
Extent version: 4.0.9

Update: if i search for author,category & device I have results.

Thanks,

**Comment by TJEvans** [comment]
Only supported in the Pro version for the Klov reporter.
https://extentreports.com/compare-editions/
