### ISSUE TITLE
ExtentReports.Core not showing Device, Author and Tag in KlovReporting

### ISSUE THREAD

**Issue by schandra09net** [extent-framework/klov#40]
ExtentReports.Core - v1.0.2
KlovServer: v0.2.5
.NET Core: v2.2.401
IDE: VSCode

// Initialized KlovReporter
var klovReporter = new ExtentKlovReporter();
klovReporter.ProjectName = appsettings["AppName"];
klovReporter.ReportName = appsettings["ReportName"];
klovReporter.InitMongoDbConnection(appsettings[constring]);
klovReporter.InitKlovServerConnection(appsettings["KlovData"]);

// Initialized ExtentReports
var extent = new AventStack.ExtentReports.ExtentReports();
extent.AddSystemInfo("Environment", "Automation Testing");
extent.AddSystemInfo("User Name", "Chandra");
extent.AttachReporter(klovReporter);

I'm trying to assign Device/Category/Author on test cases but in the report, nothing is displayed in KLOV report server builds (attached screenshot). 

ExtentTest featureName = extent.CreateTest("TestcaseName:);
featureName.AssignAuthor("Author1", "Author2");
featureName.AssignCategory("Sanity", "Regression", "TeamCity");
featureName.AssignDevice("Postman");

![image](https://user-images.githubusercontent.com/52242195/63266038-07326100-c25d-11e9-9fad-104c343b6ca9.png)

![image](https://user-images.githubusercontent.com/52242195/63266077-17e2d700-c25d-11e9-8792-bd9c11803c74.png)

![image](https://user-images.githubusercontent.com/52242195/63266090-23360280-c25d-11e9-8e1d-82ce79524fc4.png)

**Comment by TJEvans** [comment]
Those features are only supported in the Professional, paid, version of Klov.
https://extentreports.com/compare-editions/

**Comment by anshooarora** [comment]
Hello - I do not own ExtentReports.Core, it is a package created by the SimplyTest team.  There are plans of rolling out the Core version, hopefully by Jan/Feb timeframe if I continue having sufficient bandwidth.  Thank you.
