### ISSUE TITLE
Unable to contact ExtentReport (TekStorm) support team

### ISSUE THREAD

**Issue by schandra09net** [extent-framework/klov#41]
Hi Team,

First thing, this tool is pretty good and thanks ExtentReports team.

And also we wanted to have new features from ExtenReports team, and we are ready to pay for this support.
1. Have a Bar (vertical /horizontal) chart shows multiple projects with passed vs. failed test cases
2. Provide the user to generate different type of tables using test execution details, etc.

Sent couple of emails regarding same to **extentreports@tekstrom.com** and contacted using the phone and contact us form from the below link.
https://www.tekstrom.com/Contact.aspx

We are yet to get the response. (Sent email's on 6th Sep)

Can you guys let me know the most accessible way to contact your support team?

**Comment by schandra09net** [comment]
Hello Team,

Can anyone from Extent team make this meeting/contact happen?

**Comment by TJEvans** [comment]
Any luck?

**Comment by anshooarora** [comment]
@schandra09net @TJEvans Let me contact the team at Tekstrom and find out, please bare with me.  I will update you shortly.

**Comment by anshooarora** [comment]
All - Apologies for this.  Can you please try again once?
