### ISSUE TITLE
Build information not displayed

### ISSUE THREAD

**Issue by resial2** [extent-framework/klov#43]
Hello,

My klov is not displaying the test information when accessing the build tab, when I try to access the test I get the error from the image below.

![evidence](https://user-images.githubusercontent.com/22984146/65990246-a0aa8080-e461-11e9-8b71-2129aeb7110a.PNG)

The other klov tabs work normally, only this one is giving this problem, what could it be?

Informations:
Klov 0.2.5
Extent-Reports 3.1.5
Extent-CucumberAdapter 3.1.0

Thanks

**Comment by anshooarora** [comment]
This is due to the the API version 3.  Klov only works well with ExtentReports version 4+.
