### ISSUE TITLE
getting 500 error when trying to login as admin

### ISSUE THREAD

**Issue by chaitzzcode** [extent-framework/klov#45]
The set up was working fine for few days and was able to see the project and dashboards. Suddenly after few days getting 500 error. 

<img width="967" alt="Screenshot 2019-12-16 at 3 34 50 PM" src="https://user-images.githubusercontent.com/29191565/70897971-bcadcf00-2019-11ea-9380-4f48de594e12.png">

**Comment by anshooarora** [comment]
Please check with release 0.2.7 - this issue should now be resolved.
