### ISSUE TITLE
Last Build Distribution, Build Performance & Failures are not shown

### ISSUE THREAD

**Issue by NallaSandeep** [extent-framework/klov#47]
Information:
Klov 0.2.6/0.2.5/0.2.4
Extent-Reports 4.1.1

Actual:
![image](https://user-images.githubusercontent.com/42937172/72247556-202c1c00-361b-11ea-8aab-0cdb7febe29b.png)

Expected: [From http://klov.herokuapp.com/project/dashboard]
![image](https://user-images.githubusercontent.com/42937172/72247640-55386e80-361b-11ea-9fb5-ddc2bd4f8de6.png)

Note:
With klov version 0.2.3, Last Build Distribution, Build Performance & Failures are shown well.
![image](https://user-images.githubusercontent.com/42937172/72248220-a7c65a80-361c-11ea-9990-075b9fb625f1.png)

**Comment by anshooarora** [comment]
Do you see any console errors in dev tools?

Can you share a code snippet that can help me reproduce?

**Comment by NallaSandeep** [comment]
**Console error:**
Request URL: http://localhost:81/rest/projects/search/findAllByIdIn?ids=5d78daab928b8f5fb1840aa6
Request Method: GET
Status Code: 404 
Remote Address: [::1]:81
Referrer Policy: no-referrer-when-downgrade

**Code:**
```
ExtentHtmlReporter extentHtmlReporter = new ExtentHtmlReporter(
                System.getProperty("user.dir") + "/target/ExtentReport.html");
ExtentKlovReporter extentKlovReporter = new ExtentKlovReporter();
extentKlovReporter.initMongoDbConnection("localhost"); 
extentKlovReporter.setProjectName("test");
extentKlovReporter.setReportName("qa");
extentKlovReporter.initKlovServerConnection("http://localhost:81"); 
ExtentReports extentReports = new ExtentReports();
extentReports.attachReporter(extentHtmlReporter, extentKlovReporter);
extentReports.setAnalysisStrategy(AnalysisStrategy.TEST);
```

**Screenshot:**
![image](https://user-images.githubusercontent.com/42937172/73051253-5170db80-3ea8-11ea-9acb-dfa56888ed26.png)

**Comment by NallaSandeep** [comment]
To reproduce the issue, restart the klov server once the dashboard is created.

**Comment by anshooarora** [comment]
I was able to reproduce this, please check with 0.2.7 (now available).

**Comment by NallaSandeep** [comment]
With 0.2.7 version, Last Build Distribution, Build Performance charts are displayed, but Failures & Build status distribution charts are not displayed.

![image](https://user-images.githubusercontent.com/42937172/73165624-2a214500-411a-11ea-8834-1de7ee364ff2.png)

![image](https://user-images.githubusercontent.com/42937172/73165920-d19e7780-411a-11ea-909f-c76790f00338.png)

No errors are noticed in console.

**Comment by anshooarora** [comment]
Please try with 0.2.8, just pushed it with a few other minor fixes.

**Comment by NallaSandeep** [comment]
It's working as expected. Thanks @anshooarora.
