### ISSUE TITLE
Build, Test graphs missing after updating the variable "spring.data.rest.default-page-size"

### ISSUE THREAD

**Issue by sandeepgithubAcc** [extent-framework/klov#48]
**Description:**
I wanted to update the total number of builds displayed in the dashboard graph. 
So updated the "spring.data.rest.default-page-size" value to 10 from default value '6'.
And then i restarted the server
**Problem:**
After that, i am not seeing the graph. 
I Tried to change "spring.data.rest.default-page-size" back to the default value '6', still it is not working.
@anshooarora

**Comment by sandeepgithubAcc** [comment]
![image](https://user-images.githubusercontent.com/60172427/73105496-2944a500-3ec7-11ea-8128-4d1e55f5b423.png)

**Comment by anshooarora** [comment]
Please use `0.2.8`, this should now be resolved.
