### ISSUE TITLE
Can we fetch the graphical representation of the builds/tests ran over few days

### ISSUE THREAD

**Issue by sandeepgithubAcc** [extent-framework/klov#49]
**Description:**
Currently the reporting shows the "Tests Executed Today", "Builds Executed Today".
Instead of that, can we alter the feature and display graph for "Tests Executed the week" or "Tests Executed the 10 days".

Is it possible by changing something from "application.properties".. Or anything programmatically..

**Comment by anshooarora** [comment]
This is not configurable at present.  Marking this ticket as an enhancement.

**Comment by sandeepgithubAcc** [comment]
Okay, can we configure it by using the jar file ? is it legal... 

if not, are you planning to deploy it in the near future ? @anshooarora

**Comment by NallaSandeep** [comment]
In below google stock market trend, user is given choice to select the time period. A similar option would be very helpful in klov dashboard too.

![image](https://user-images.githubusercontent.com/42937172/73337637-be1a1a80-429a-11ea-9e81-c9ccd6159f3f.png)

**Comment by anshooarora** [comment]
@sandeepgithubAcc @NallaSandeep  Marked this as an enhancement.
