### ISSUE TITLE
Base64 Screenshots aren't visible 

### ISSUE THREAD

**Issue by letmejustfixthat** [extent-framework/klov#6]
Adding Base64 Screenhots (using 0.2.2) doesn't seem to work in the Klov browser, they are just not shown. 

    /**
     * Logs @param msg, embeds @param screenshot and logs the current url via @param driver. Finally fail()
     */
    public static void logAndFail(final String msg, final ExtentTest test, final WebDriver driver, final String screenshot) {
        test.fail(msg);
        if(screenshot != null) {
            // Doesn't work in HTML Report AND Klov:
            test.addScreenCaptureFromBase64String(screenshot);

            // Doesn't work in Klov:
            try {
                test.fail("Screenshot", MediaEntityBuilder.createScreenCaptureFromBase64String(screenshot).build());
            }
            catch(IOException e) {
                e.printStackTrace();
            }

            // Works for both:
            test.fail("<img src=\"" + screenshot + "\">");
        }
        test.fail("Current URL: " + driver.getCurrentUrl());
        fail(msg);
    }

Any ideas what could be wrong? The base64 String looks like the following: `data:image/png;base64,...`

**Comment by anshooarora** [comment]
I am able to reproduce, thanks. Will release a fix by tomorrow along with a few others.

**Comment by letmejustfixthat** [comment]
Both variants still don't work in 0.2.3 for me. With `test.addScreenCaptureFromBase64String()` I can't see a result anywhere (klov reporter, html reporter) and with the `MediaEntityBuilder` still only works in the html reporter

**Comment by anshooarora** [comment]
You also need to use extentreports:4.0.7.
