### ISSUE TITLE
Builds overview

### ISSUE THREAD

**Issue by letmejustfixthat** [extent-framework/klov#8]
There are a few bugs in the build overview:

The close button doesn't seem to have any function
![screenhunter_169 jan 15 09 34](https://user-images.githubusercontent.com/12950399/51168634-1bb71100-18aa-11e9-9265-2ddad765e102.jpg)

Clicking the "View Failed" button leads to an empty page with an error on the console
![screenhunter_170 jan 15 09 45](https://user-images.githubusercontent.com/12950399/51168706-515bfa00-18aa-11e9-922d-5406a892e1d2.jpg)

**Comment by anshooarora** [comment]
The close button just closes the popup, which is the same as clicking anywhere else on the UI.  I don't remember why this was added, maybe for smaller displays which kept the dropdown enabled even after removing focus.  I guess keeping it is fine.

The "View Failed" is indeed a bug.
