### ISSUE TITLE
MarkupHelper doesn't work in KlovReport

### ISSUE THREAD

**Issue by letmejustfixthat** [extent-framework/klov#9]
The MarkupHelper result is currently not visible in the Klov Report. In the HTML report it works as expected.

    test.fail(MarkupHelper.createCodeBlock(res.body().print(), CodeLanguage.JSON));

`res` is a REST-assured response body and will print the following:

    [{"errorText":"some text","errorCode":"UNCLASSIFIED"}]

I'm using the current version 0.2.3

**Comment by anshooarora** [comment]
This is due to the underlying source for the json prettifier (json-tree) not being available in Klov.  I will add this along with a few other fixes and release 0.2.4.
